-- M1: người dùng, nông trại, lô đất, danh mục cây trồng.
-- Ràng buộc CHECK/UNIQUE/FK phản chiếu quy tắc nghiệp vụ (docs/architecture.md, mục 6)
-- làm lớp phòng thủ cuối sau Bean Validation và bất biến domain.

CREATE TABLE app_user (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    version     BIGINT       NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_app_user_email UNIQUE (email)
);

CREATE TABLE farm (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id    BIGINT       NOT NULL,
    name        VARCHAR(120) NOT NULL,
    location    VARCHAR(255),
    version     BIGINT       NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_farm_owner FOREIGN KEY (owner_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_farm_name_not_blank CHECK (btrim(name) <> '')
);
-- PostgreSQL không tự tạo index cho khóa ngoại
CREATE INDEX idx_farm_owner_id ON farm (owner_id);

CREATE TABLE plot (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id     BIGINT           NOT NULL,
    name        VARCHAR(60)      NOT NULL,
    area_m2     DOUBLE PRECISION NOT NULL,
    soil_type   VARCHAR(60),
    version     BIGINT           NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ      NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ      NOT NULL DEFAULT now(),
    CONSTRAINT fk_plot_farm FOREIGN KEY (farm_id) REFERENCES farm (id) ON DELETE RESTRICT,
    CONSTRAINT ck_plot_area_positive CHECK (area_m2 > 0),               -- BR-01
    CONSTRAINT ck_plot_name_not_blank CHECK (btrim(name) <> '')         -- BR-01
);
-- BR-01: tên lô duy nhất trong nông trại (không phân biệt hoa thường).
-- Cột đầu farm_id giúp index này phục vụ luôn cho khóa ngoại.
CREATE UNIQUE INDEX uq_plot_farm_name ON plot (farm_id, lower(name));

CREATE TABLE crop (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(80) NOT NULL,
    variety             VARCHAR(80),
    is_perennial        BOOLEAN     NOT NULL,
    season_start_month  INTEGER,
    version             BIGINT      NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_crop_name_not_blank CHECK (btrim(name) <> ''),
    -- BR-05a: cây lâu năm có tháng bắt đầu niên vụ 1–12, cây ngắn ngày thì không
    CONSTRAINT ck_crop_season_start_month CHECK (
        (is_perennial AND season_start_month BETWEEN 1 AND 12)
        OR (NOT is_perennial AND season_start_month IS NULL)
    )
);
CREATE UNIQUE INDEX uq_crop_name_variety ON crop (lower(name), lower(coalesce(variety, '')));
