-- M2: lứa trồng — xen canh (nhiều lứa trên một lô) và vòng đời.

CREATE TABLE planting (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plot_id        BIGINT       NOT NULL,
    crop_id        BIGINT       NOT NULL,
    planting_date  DATE         NOT NULL,
    tree_count     INTEGER      NOT NULL,
    status         VARCHAR(20)  NOT NULL,
    end_date       DATE,
    end_reason     VARCHAR(20),
    end_note       VARCHAR(255),
    version        BIGINT       NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- BR-10: FK RESTRICT giữ lịch sử sử dụng đất
    CONSTRAINT fk_planting_plot FOREIGN KEY (plot_id) REFERENCES plot (id) ON DELETE RESTRICT,
    CONSTRAINT fk_planting_crop FOREIGN KEY (crop_id) REFERENCES crop (id) ON DELETE RESTRICT,
    CONSTRAINT ck_planting_tree_count_positive CHECK (tree_count > 0),                        -- BR-02
    CONSTRAINT ck_planting_status CHECK (status IN ('GROWING', 'PRODUCING', 'TERMINATED')),
    CONSTRAINT ck_planting_end_reason CHECK (
        end_reason IN ('MARKET', 'PEST_DISEASE', 'WEATHER', 'OLD_AGE', 'OTHER')),
    -- BR-04: đã kết thúc thì phải có ngày và lý do; chưa kết thúc thì không có
    CONSTRAINT ck_planting_termination_consistent CHECK (
        (status = 'TERMINATED' AND end_date IS NOT NULL AND end_reason IS NOT NULL)
        OR (status <> 'TERMINATED' AND end_date IS NULL AND end_reason IS NULL AND end_note IS NULL)
    ),
    CONSTRAINT ck_planting_end_not_before_start CHECK (end_date >= planting_date)             -- BR-04
);

CREATE INDEX idx_planting_plot_id ON planting (plot_id);
CREATE INDEX idx_planting_crop_id ON planting (crop_id);
-- Truy vấn nóng nhất của Epic B: "lô đang có cây gì" — partial index chỉ chứa lứa đang canh tác
CREATE INDEX idx_planting_active_by_plot ON planting (plot_id) WHERE status <> 'TERMINATED';
