-- M3: niên vụ, nhật ký canh tác và thu hoạch (Epic D, E).
-- Niên vụ là dữ liệu dẫn xuất: SeasonPolicy tính cửa sổ từ CROP.season_start_month,
-- SeasonAssigner tạo bản ghi khi có hoạt động/thu hoạch đầu tiên rơi vào (BR-05a, ADR-7).

CREATE TABLE season (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planting_id  BIGINT      NOT NULL,
    year         INTEGER     NOT NULL,
    start_date   DATE        NOT NULL,
    end_date     DATE,
    version      BIGINT      NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_season_planting FOREIGN KEY (planting_id) REFERENCES planting (id) ON DELETE RESTRICT,
    -- BR-06: end_date NULL nghĩa là niên vụ đang diễn ra (cây ngắn ngày)
    CONSTRAINT ck_season_dates CHECK (end_date IS NULL OR end_date >= start_date)
);
-- BR-05: mỗi lứa trồng tối đa một niên vụ cho mỗi năm.
-- Cột đầu planting_id giúp index này phục vụ luôn cho khóa ngoại.
CREATE UNIQUE INDEX uq_season_planting_year ON season (planting_id, year);

CREATE TABLE activity (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id      BIGINT        NOT NULL,
    type           VARCHAR(20)   NOT NULL,
    activity_date  DATE          NOT NULL,
    cost           NUMERIC(15, 2) NOT NULL,
    note           VARCHAR(255),
    version        BIGINT        NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_activity_season FOREIGN KEY (season_id) REFERENCES season (id) ON DELETE RESTRICT,
    CONSTRAINT ck_activity_type CHECK (
        type IN ('WATERING', 'FERTILIZING', 'SPRAYING', 'WEEDING', 'PRUNING', 'OTHER')),
    CONSTRAINT ck_activity_cost_not_negative CHECK (cost >= 0),                              -- BR-08
    -- BR-12: loại OTHER không có ghi chú thì dòng nhật ký không còn ý nghĩa
    CONSTRAINT ck_activity_other_has_note CHECK (type <> 'OTHER' OR btrim(coalesce(note, '')) <> '')
);
-- Truy vấn nóng: nhật ký của một niên vụ, mới nhất trước, có phân trang.
-- Cột đầu season_id phục vụ luôn cho khóa ngoại.
CREATE INDEX idx_activity_season_date ON activity (season_id, activity_date DESC, id DESC);

CREATE TABLE harvest (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id     BIGINT           NOT NULL,
    harvest_date  DATE             NOT NULL,
    quantity_kg   DOUBLE PRECISION NOT NULL,
    revenue       NUMERIC(15, 2)   NOT NULL,
    version       BIGINT           NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ      NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ      NOT NULL DEFAULT now(),
    CONSTRAINT fk_harvest_season FOREIGN KEY (season_id) REFERENCES season (id) ON DELETE RESTRICT,
    CONSTRAINT ck_harvest_quantity_positive CHECK (quantity_kg > 0),                         -- BR-08
    CONSTRAINT ck_harvest_revenue_not_negative CHECK (revenue >= 0)                          -- BR-08
);
CREATE INDEX idx_harvest_season_date ON harvest (season_id, harvest_date DESC, id DESC);
